### ISSUE TITLE
[bug] Backups Failing

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/lightning-terminal-startos#27] opened 2024-01-29 17:57 UTC
Reported by a few users.  Currently the fix seems to be an uninstall and re-install.  
![image](https://github.com/Start9Labs/lightning-terminal-startos/assets/39687477/e42000da-dcf2-434b-88e7-daa3f7c095d8)

**Comment by Dominion5254** [comment] 2024-01-29 22:31
I have not been able to reproduce this with LiT 0.12.2 using StartOS 0.3.5.1. Do you have LiT and StartOS versions for users that have encountered this error? Backup target format would be helpful as well.

My understanding is StartOS 0.3.5.1 does not set permissions on backups, so it would seem the user is on an older version of StartOS? Otherwise there might be an issue with the format of the backup target.

**Comment by Dominion5254** [comment] 2024-04-01 17:47
Fixed by #29

**Closed by Dominion5254** 2024-04-01 17:47 UTC

**Comment by WinstonSmith73** [comment] 2025-04-23 17:02
Very similar error for me just now on my Start9 server

<img width="903" alt="Image" src="https://github.com/user-attachments/assets/10d2a663-a744-4a5a-8d45-a0dd10c6ffa0" />

**Comment by Dominion5254** [comment] 2025-04-23 17:07
@WinstonSmith73 this looks like an error with Monerod and should be a new issue on that [repo](https://github.com/kn0wmad/monerod-startos)

**Comment by WinstonSmith73** [comment] 2025-04-23 17:08
> [@WinstonSmith73](https://github.com/WinstonSmith73) this looks like an error with Monerod and should be a new issue on that [repo](https://github.com/kn0wmad/monerod-startos)

TY will post there with more info.
